<?php
namespace App\Filament\Pages;

use App\Filament\Resources\Expenses\Widgets\ExpenseOverview;
use App\Filament\Resources\Expenses\Widgets\ExpensesChart;
use App\Filament\Resources\LoanGivens\Widgets\LoanGivenOverview;
use App\Filament\Resources\LoanTakens\Widgets\LoanTakenOverview;
use Filament\Pages\Dashboard as BaseDashboard;

class Dashboard extends BaseDashboard
{
    // ...
    public function getColumns(): int|array
    {
        return [
            'md' => 4,
            'xl' => 5,
        ];
    }
//    protected function getHeaderWidgets(): array
//    {
//        return [
//            ExpenseOverview::class,
//        ];
//    }
    public function getWidgets(): array
    {
        return [
            ExpenseOverview::make(['Dashboard'=>true]),
            ExpensesChart::class,
            LoanTakenOverview::make(['Dashboard'=>true]),
            LoanGivenOverview::make(['Dashboard'=>true]),
        ]; // TODO: Change the autogenerated stub
    }
}
